//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ip_prj.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeTable", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class TimeTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Class_Room_LabField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Class_Room_Lab_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class_Room_Lab {
            get {
                return this.Class_Room_LabField;
            }
            set {
                if ((object.ReferenceEquals(this.Class_Room_LabField, value) != true)) {
                    this.Class_Room_LabField = value;
                    this.RaisePropertyChanged("Class_Room_Lab");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class_Room_Lab_ID {
            get {
                return this.Class_Room_Lab_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.Class_Room_Lab_IDField, value) != true)) {
                    this.Class_Room_Lab_IDField = value;
                    this.RaisePropertyChanged("Class_Room_Lab_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject {
            get {
                return this.SubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectField, value) != true)) {
                    this.SubjectField = value;
                    this.RaisePropertyChanged("Subject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Teacher {
            get {
                return this.TeacherField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherField, value) != true)) {
                    this.TeacherField = value;
                    this.RaisePropertyChanged("Teacher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Time {
            get {
                return this.TimeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeField, value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Staff", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Staff : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Date_of_birthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DesignationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Joined_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NICField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date_of_birth {
            get {
                return this.Date_of_birthField;
            }
            set {
                if ((object.ReferenceEquals(this.Date_of_birthField, value) != true)) {
                    this.Date_of_birthField = value;
                    this.RaisePropertyChanged("Date_of_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Designation {
            get {
                return this.DesignationField;
            }
            set {
                if ((object.ReferenceEquals(this.DesignationField, value) != true)) {
                    this.DesignationField = value;
                    this.RaisePropertyChanged("Designation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name {
            get {
                return this.First_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_nameField, value) != true)) {
                    this.First_nameField = value;
                    this.RaisePropertyChanged("First_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Joined_date {
            get {
                return this.Joined_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.Joined_dateField, value) != true)) {
                    this.Joined_dateField = value;
                    this.RaisePropertyChanged("Joined_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIC {
            get {
                return this.NICField;
            }
            set {
                if ((object.ReferenceEquals(this.NICField, value) != true)) {
                    this.NICField = value;
                    this.RaisePropertyChanged("NIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qualifications {
            get {
                return this.QualificationsField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationsField, value) != true)) {
                    this.QualificationsField = value;
                    this.RaisePropertyChanged("Qualifications");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_name {
            get {
                return this.User_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_nameField, value) != true)) {
                    this.User_nameField = value;
                    this.RaisePropertyChanged("User_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Admission_noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string First_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Last_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SectionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Admission_no {
            get {
                return this.Admission_noField;
            }
            set {
                if ((object.ReferenceEquals(this.Admission_noField, value) != true)) {
                    this.Admission_noField = value;
                    this.RaisePropertyChanged("Admission_no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Class {
            get {
                return this.ClassField;
            }
            set {
                if ((object.ReferenceEquals(this.ClassField, value) != true)) {
                    this.ClassField = value;
                    this.RaisePropertyChanged("Class");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First_name {
            get {
                return this.First_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.First_nameField, value) != true)) {
                    this.First_nameField = value;
                    this.RaisePropertyChanged("First_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Grade {
            get {
                return this.GradeField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeField, value) != true)) {
                    this.GradeField = value;
                    this.RaisePropertyChanged("Grade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last_name {
            get {
                return this.Last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Last_nameField, value) != true)) {
                    this.Last_nameField = value;
                    this.RaisePropertyChanged("Last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Section {
            get {
                return this.SectionField;
            }
            set {
                if ((object.ReferenceEquals(this.SectionField, value) != true)) {
                    this.SectionField = value;
                    this.RaisePropertyChanged("Section");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_name {
            get {
                return this.User_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.User_nameField, value) != true)) {
                    this.User_nameField = value;
                    this.RaisePropertyChanged("User_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="newstfshw", Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    [System.SerializableAttribute()]
    public partial class newstfshw : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ip_prj.ServiceReference1.CompositeType GetDataUsingDataContract(ip_prj.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ip_prj.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddComputingTimeTable", ReplyAction="http://tempuri.org/IService1/AddComputingTimeTableResponse")]
        int AddComputingTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddComputingTimeTable", ReplyAction="http://tempuri.org/IService1/AddComputingTimeTableResponse")]
        System.Threading.Tasks.Task<int> AddComputingTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddManagementTimeTable", ReplyAction="http://tempuri.org/IService1/AddManagementTimeTableResponse")]
        int AddManagementTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddManagementTimeTable", ReplyAction="http://tempuri.org/IService1/AddManagementTimeTableResponse")]
        System.Threading.Tasks.Task<int> AddManagementTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/AddEngineeringTimeTableResponse")]
        int AddEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/AddEngineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> AddEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComTimeTable", ReplyAction="http://tempuri.org/IService1/GetComTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetComTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetComTimeTable", ReplyAction="http://tempuri.org/IService1/GetComTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetComTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetmngTimeTable", ReplyAction="http://tempuri.org/IService1/GetmngTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetmngTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetmngTimeTable", ReplyAction="http://tempuri.org/IService1/GetmngTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetmngTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetengTimeTable", ReplyAction="http://tempuri.org/IService1/GetengTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetengTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetengTimeTable", ReplyAction="http://tempuri.org/IService1/GetengTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetengTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStaffTable", ReplyAction="http://tempuri.org/IService1/AddStaffTableResponse")]
        int AddStaffTable(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStaffTable", ReplyAction="http://tempuri.org/IService1/AddStaffTableResponse")]
        System.Threading.Tasks.Task<int> AddStaffTableAsync(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudentTable", ReplyAction="http://tempuri.org/IService1/AddStudentTableResponse")]
        int AddStudentTable(ip_prj.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddStudentTable", ReplyAction="http://tempuri.org/IService1/AddStudentTableResponse")]
        System.Threading.Tasks.Task<int> AddStudentTableAsync(ip_prj.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpEngineeringTimeTableResponse")]
        int UpEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpEngineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> UpEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpcomineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpcomineeringTimeTableResponse")]
        int UpcomineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpcomineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpcomineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> UpcomineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpmngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpmngineeringTimeTableResponse")]
        int UpmngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpmngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/UpmngineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> UpmngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelEngineeringTimeTableResponse")]
        int DelEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelEngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelEngineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> DelEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelcomineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelcomineeringTimeTableResponse")]
        int DelcomineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelcomineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelcomineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> DelcomineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelmngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelmngineeringTimeTableResponse")]
        int DelmngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DelmngineeringTimeTable", ReplyAction="http://tempuri.org/IService1/DelmngineeringTimeTableResponse")]
        System.Threading.Tasks.Task<int> DelmngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpStaffTable", ReplyAction="http://tempuri.org/IService1/UpStaffTableResponse")]
        int UpStaffTable(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpStaffTable", ReplyAction="http://tempuri.org/IService1/UpStaffTableResponse")]
        System.Threading.Tasks.Task<int> UpStaffTableAsync(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpStudentTable", ReplyAction="http://tempuri.org/IService1/UpStudentTableResponse")]
        int UpStudentTable(ip_prj.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpStudentTable", ReplyAction="http://tempuri.org/IService1/UpStudentTableResponse")]
        System.Threading.Tasks.Task<int> UpStudentTableAsync(ip_prj.ServiceReference1.Student st);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delstaff", ReplyAction="http://tempuri.org/IService1/DelstaffResponse")]
        int Delstaff(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delstaff", ReplyAction="http://tempuri.org/IService1/DelstaffResponse")]
        System.Threading.Tasks.Task<int> DelstaffAsync(ip_prj.ServiceReference1.Staff s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delstudent", ReplyAction="http://tempuri.org/IService1/DelstudentResponse")]
        int Delstudent(ip_prj.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delstudent", ReplyAction="http://tempuri.org/IService1/DelstudentResponse")]
        System.Threading.Tasks.Task<int> DelstudentAsync(ip_prj.ServiceReference1.Student s);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstf", ReplyAction="http://tempuri.org/IService1/getstfResponse")]
        ip_prj.ServiceReference1.Staff[] getstf();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstf", ReplyAction="http://tempuri.org/IService1/getstfResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff[]> getstfAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstu", ReplyAction="http://tempuri.org/IService1/getstuResponse")]
        ip_prj.ServiceReference1.Student[] getstu();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstu", ReplyAction="http://tempuri.org/IService1/getstuResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student[]> getstuAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstfIDnEmail", ReplyAction="http://tempuri.org/IService1/getstfIDnEmailResponse")]
        ip_prj.ServiceReference1.newstfshw[] getstfIDnEmail();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getstfIDnEmail", ReplyAction="http://tempuri.org/IService1/getstfIDnEmailResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.newstfshw[]> getstfIDnEmailAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentComTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentComTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetCurrentComTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentComTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentComTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentComTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentMngTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentMngTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetCurrentMngTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentMngTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentMngTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentMngTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentEngTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentEngTimeTableResponse")]
        ip_prj.ServiceReference1.TimeTable[] GetCurrentEngTimeTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCurrentEngTimeTable", ReplyAction="http://tempuri.org/IService1/GetCurrentEngTimeTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentEngTimeTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Userlogine", ReplyAction="http://tempuri.org/IService1/UserlogineResponse")]
        ip_prj.ServiceReference1.Staff[] Userlogine();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Userlogine", ReplyAction="http://tempuri.org/IService1/UserlogineResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff[]> UserlogineAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchStaff", ReplyAction="http://tempuri.org/IService1/SearchStaffResponse")]
        ip_prj.ServiceReference1.Staff SearchStaff(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchStaff", ReplyAction="http://tempuri.org/IService1/SearchStaffResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff> SearchStaffAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchStudent", ReplyAction="http://tempuri.org/IService1/SearchStudentResponse")]
        ip_prj.ServiceReference1.Student SearchStudent(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchStudent", ReplyAction="http://tempuri.org/IService1/SearchStudentResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student> SearchStudentAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebLogin", ReplyAction="http://tempuri.org/IService1/WebLoginResponse")]
        ip_prj.ServiceReference1.Staff WebLogin(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebLogin", ReplyAction="http://tempuri.org/IService1/WebLoginResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff> WebLoginAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebLogin2", ReplyAction="http://tempuri.org/IService1/WebLogin2Response")]
        ip_prj.ServiceReference1.Student WebLogin2(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/WebLogin2", ReplyAction="http://tempuri.org/IService1/WebLogin2Response")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student> WebLogin2Async(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchComputingTable", ReplyAction="http://tempuri.org/IService1/SearchComputingTableResponse")]
        ip_prj.ServiceReference1.TimeTable SearchComputingTable(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchComputingTable", ReplyAction="http://tempuri.org/IService1/SearchComputingTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchComputingTableAsync(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchManagementTable", ReplyAction="http://tempuri.org/IService1/SearchManagementTableResponse")]
        ip_prj.ServiceReference1.TimeTable SearchManagementTable(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchManagementTable", ReplyAction="http://tempuri.org/IService1/SearchManagementTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchManagementTableAsync(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchengineeringTable", ReplyAction="http://tempuri.org/IService1/SearchengineeringTableResponse")]
        ip_prj.ServiceReference1.TimeTable SearchengineeringTable(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SearchengineeringTable", ReplyAction="http://tempuri.org/IService1/SearchengineeringTableResponse")]
        System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchengineeringTableAsync(string no);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ip_prj.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ip_prj.ServiceReference1.IService1>, ip_prj.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ip_prj.ServiceReference1.CompositeType GetDataUsingDataContract(ip_prj.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ip_prj.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public int AddComputingTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddComputingTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> AddComputingTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddComputingTimeTableAsync(t);
        }
        
        public int AddManagementTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddManagementTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> AddManagementTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddManagementTimeTableAsync(t);
        }
        
        public int AddEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddEngineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> AddEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.AddEngineeringTimeTableAsync(t);
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetComTimeTable() {
            return base.Channel.GetComTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetComTimeTableAsync() {
            return base.Channel.GetComTimeTableAsync();
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetmngTimeTable() {
            return base.Channel.GetmngTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetmngTimeTableAsync() {
            return base.Channel.GetmngTimeTableAsync();
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetengTimeTable() {
            return base.Channel.GetengTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetengTimeTableAsync() {
            return base.Channel.GetengTimeTableAsync();
        }
        
        public int AddStaffTable(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.AddStaffTable(s);
        }
        
        public System.Threading.Tasks.Task<int> AddStaffTableAsync(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.AddStaffTableAsync(s);
        }
        
        public int AddStudentTable(ip_prj.ServiceReference1.Student st) {
            return base.Channel.AddStudentTable(st);
        }
        
        public System.Threading.Tasks.Task<int> AddStudentTableAsync(ip_prj.ServiceReference1.Student st) {
            return base.Channel.AddStudentTableAsync(st);
        }
        
        public int UpEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpEngineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> UpEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpEngineeringTimeTableAsync(t);
        }
        
        public int UpcomineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpcomineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> UpcomineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpcomineeringTimeTableAsync(t);
        }
        
        public int UpmngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpmngineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> UpmngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.UpmngineeringTimeTableAsync(t);
        }
        
        public int DelEngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelEngineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> DelEngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelEngineeringTimeTableAsync(t);
        }
        
        public int DelcomineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelcomineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> DelcomineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelcomineeringTimeTableAsync(t);
        }
        
        public int DelmngineeringTimeTable(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelmngineeringTimeTable(t);
        }
        
        public System.Threading.Tasks.Task<int> DelmngineeringTimeTableAsync(ip_prj.ServiceReference1.TimeTable t) {
            return base.Channel.DelmngineeringTimeTableAsync(t);
        }
        
        public int UpStaffTable(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.UpStaffTable(s);
        }
        
        public System.Threading.Tasks.Task<int> UpStaffTableAsync(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.UpStaffTableAsync(s);
        }
        
        public int UpStudentTable(ip_prj.ServiceReference1.Student st) {
            return base.Channel.UpStudentTable(st);
        }
        
        public System.Threading.Tasks.Task<int> UpStudentTableAsync(ip_prj.ServiceReference1.Student st) {
            return base.Channel.UpStudentTableAsync(st);
        }
        
        public int Delstaff(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.Delstaff(s);
        }
        
        public System.Threading.Tasks.Task<int> DelstaffAsync(ip_prj.ServiceReference1.Staff s) {
            return base.Channel.DelstaffAsync(s);
        }
        
        public int Delstudent(ip_prj.ServiceReference1.Student s) {
            return base.Channel.Delstudent(s);
        }
        
        public System.Threading.Tasks.Task<int> DelstudentAsync(ip_prj.ServiceReference1.Student s) {
            return base.Channel.DelstudentAsync(s);
        }
        
        public ip_prj.ServiceReference1.Staff[] getstf() {
            return base.Channel.getstf();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff[]> getstfAsync() {
            return base.Channel.getstfAsync();
        }
        
        public ip_prj.ServiceReference1.Student[] getstu() {
            return base.Channel.getstu();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student[]> getstuAsync() {
            return base.Channel.getstuAsync();
        }
        
        public ip_prj.ServiceReference1.newstfshw[] getstfIDnEmail() {
            return base.Channel.getstfIDnEmail();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.newstfshw[]> getstfIDnEmailAsync() {
            return base.Channel.getstfIDnEmailAsync();
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetCurrentComTimeTable() {
            return base.Channel.GetCurrentComTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentComTimeTableAsync() {
            return base.Channel.GetCurrentComTimeTableAsync();
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetCurrentMngTimeTable() {
            return base.Channel.GetCurrentMngTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentMngTimeTableAsync() {
            return base.Channel.GetCurrentMngTimeTableAsync();
        }
        
        public ip_prj.ServiceReference1.TimeTable[] GetCurrentEngTimeTable() {
            return base.Channel.GetCurrentEngTimeTable();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable[]> GetCurrentEngTimeTableAsync() {
            return base.Channel.GetCurrentEngTimeTableAsync();
        }
        
        public ip_prj.ServiceReference1.Staff[] Userlogine() {
            return base.Channel.Userlogine();
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff[]> UserlogineAsync() {
            return base.Channel.UserlogineAsync();
        }
        
        public ip_prj.ServiceReference1.Staff SearchStaff(string id) {
            return base.Channel.SearchStaff(id);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff> SearchStaffAsync(string id) {
            return base.Channel.SearchStaffAsync(id);
        }
        
        public ip_prj.ServiceReference1.Student SearchStudent(string id) {
            return base.Channel.SearchStudent(id);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student> SearchStudentAsync(string id) {
            return base.Channel.SearchStudentAsync(id);
        }
        
        public ip_prj.ServiceReference1.Staff WebLogin(string Id) {
            return base.Channel.WebLogin(Id);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Staff> WebLoginAsync(string Id) {
            return base.Channel.WebLoginAsync(Id);
        }
        
        public ip_prj.ServiceReference1.Student WebLogin2(string Id) {
            return base.Channel.WebLogin2(Id);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.Student> WebLogin2Async(string Id) {
            return base.Channel.WebLogin2Async(Id);
        }
        
        public ip_prj.ServiceReference1.TimeTable SearchComputingTable(string no) {
            return base.Channel.SearchComputingTable(no);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchComputingTableAsync(string no) {
            return base.Channel.SearchComputingTableAsync(no);
        }
        
        public ip_prj.ServiceReference1.TimeTable SearchManagementTable(string no) {
            return base.Channel.SearchManagementTable(no);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchManagementTableAsync(string no) {
            return base.Channel.SearchManagementTableAsync(no);
        }
        
        public ip_prj.ServiceReference1.TimeTable SearchengineeringTable(string no) {
            return base.Channel.SearchengineeringTable(no);
        }
        
        public System.Threading.Tasks.Task<ip_prj.ServiceReference1.TimeTable> SearchengineeringTableAsync(string no) {
            return base.Channel.SearchengineeringTableAsync(no);
        }
    }
}
